# Generated by Django 4.1.3 on 2022-12-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("s_id", models.IntegerField(primary_key=True, serialize=False)),
                ("s_name", models.CharField(max_length=100)),
                ("s_mail", models.EmailField(max_length=254)),
                ("s_reemail", models.EmailField(max_length=254)),
            ],
        ),
    ]
