# Generated by Django 4.1.3 on 2022-12-28 14:29

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="s_id",
            field=models.IntegerField(
                primary_key=True,
                serialize=False,
                validators=[app.models.check_id, app.models.check_n],
            ),
        ),
    ]
