# Generated by Django 4.1.3 on 2022-12-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_student_s_moblie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="s_moblie",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
