# Generated by Django 4.1.3 on 2022-12-28 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_student_s_moblie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="s_moblie",
            field=models.CharField(
                default="1234567890",
                max_length=10,
                validators=[
                    django.core.validators.MaxLengthValidator(10),
                    django.core.validators.MinLengthValidator(10),
                ],
            ),
        ),
    ]
